name: DragonEggHunt
version: '\${project.version}'
main: com.zartu.dragonegghunt.DragonEggHunt
api-version: '1.21'
authors: [Zartu]
description: A CTF style Dragon Egg plugin with tracking and leaderboards.

commands:
  eggtrack:
    description: Gives a vague location of the Dragon Egg.
    permission: dragonegg.track
  eggsetspawn:
    description: Sets the safe respawn location for the Egg.
    permission: dragonegg.admin
  eggreset:
    description: Spawns the custom egg item for testing.
  eggleaderboard:
    description: Displays who has held the egg the longest.
    permission: dragonegg.track
    permission: dragonegg.mod
  egglocation:
    description: Get exact location of the egg.
    permission: dragonegg.mod

permissions:
  dragonegg.track:
    description: Allows tracking the egg
    default: true
  dragonegg.mod:
    description: Moderator commands
    default: op
  dragonegg.admin:
    description: Admin commands
    default: op